### ISSUE TITLE
Caching responses

### ISSUE THREAD

**Issue by riccardofelluga** [booster-proj/booster#44]
**Is your feature request related to a problem? Please describe.**
Sometimes the same request is repeated over and over by the user (e.g. loading always the same website or always asking the same endpoint for the same data), this can lead to useless requests blocking/congesting the network.

**Describe the solution you'd like**
Booster could implement a feature to detect identical/similar responses and a caching system able to partially and/or totally store them. 

**Additional context**
Caching is already a fairly common practice among proxy servers.

**Comment by jecoz** [comment]
Hey @riccardofelluga thanks for your suggestion 👍 Unfortunately, as probably `booster` will no longer be implemented using proxies, I don't think this issue will be relevant in the future. Furthermore I think that, as soon as, as you stated, it is a common practise to build caching proxies, booster as it is in its latest release could be chained to a caching proxy to obtain the same result!
